#007. Weather Observation Station 3
SELECT DISTINCT CITY FROM STATION WHERE (ID % 2) = 0;


#008. Weather Observation Station 4
SELECT COUNT(CITY) - COUNT(DISTINCT CITY)
FROM STATION;

#009. Weather Observation Station 5
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY),CITY; 
SELECT TOP 1 CITY, LEN(CITY) FROM STATION ORDER BY LEN(CITY) DESC,CITY;

##010. Weather Observation Station 6
SELECT DISTINCT CITY
FROM STATION
WHERE CITY  LIKE '[A,E,I,O,U]%'

##011. Weather Observation Station 7
SELECT DISTINCT CITY
FROM STATION
WHERE CITY  LIKE '%[A,E,I,O,U]'

##012. Weather Observation Station 8
SELECT DISTINCT CITY
FROM STATION
WHERE CITY  LIKE '%[A,E,I,O,U]' AND CITY  LIKE '[A,E,I,O,U]%' 

##013. Weather Observation Station 9
SELECT DISTINCT CITY
FROM STATION
WHERE CITY  NOT LIKE '[A,E,I,O,U]%'

##014. Weather Observation Station 10
SELECT DISTINCT CITY
FROM STATION
WHERE CITY  NOT LIKE '%[A,E,I,O,U]'